sonar.host.url=https://sonarcloud.io
sonar.organization=swen-777-cryptography
sonar.projectKey=swen-777-cryptography_cryptography-qa-analysis

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/target/**,vectors/**,docs/**
