name: Rust SonarQube Cloud Scan

on:
  push:
    branches: ["main"]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Disabling shallow clones is recommended for accurate blame info

      - name: Install Rust and Clippy
        run: |
          rustup update stable
          rustup component add clippy

      - name: Official SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


